# -*- coding: utf-8 -*-
"""
/***************************************************************************
 pol_toolkit
                                 A QGIS plugin
 City planning Database administration toolkit
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-12-22
        copyright            : (C) 2021 by Geomeletitiki SA/ Municipality of Acharnes
        email                : efstathios.lyberis@geomeletitiki.gr
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load pol_toolkit class from file pol_toolkit.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .pol_toolkit import pol_toolkit
    return pol_toolkit(iface)
